controller_list:
  - name: "sagittarius_arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: [joint1, joint2, joint3, joint4, joint5, joint6]
  - name: "sagittarius_gripper_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: [joint_gripper_right, joint_gripper_left]
