# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

sagittarius_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  gains: # Required because we're controlling an effort interface
    joint1: {p: 500.0,  d: 1.0, i: 5.0}
    joint2: {p: 800.0,  d: 1.0, i: 10.0}
    joint3: {p: 800.0,  d: 1.0, i: 10.0}
    joint4: {p: 200.0,  d: 0, i: 0}
    joint5: {p: 100.0,  d: 1.0, i: 3.0}
    joint6: {p: 20.0,  d: 0, i: 0}
# joint4: {p: 5.0,  d: 0, i: 0}
  constraints:
    goal_time: 0.2
    joint1:
      goal: 0.1
      trajectory: 0.2
    joint2:
      goal: 0.2
      trajectory: 0.2
    joint3:
      goal: 0.2
      trajectory: 0.2
    joint4:
      goal: 0.2
      trajectory: 0.2
    joint5:
      goal: 0.2
      trajectory: 0.2
    joint6:
      goal: 0.2
      trajectory: 0.2

sagittarius_gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_gripper_left
    - joint_gripper_right
  gains:
    joint_gripper_left: {p: 100.0,  d: 1.0, i: 0.0}
    joint_gripper_right: {p: 100.0,  d: 1.0, i: 0.0}
